### ISSUE TITLE
Bug: Sending transactions

### ISSUE THREAD

**Issue by snowsledge** [AndreiD/xzil-wallet#12]
After clicking the `SEND` button, the loading screen appears for a split second and disappears.
Waited for 5 minutes (2 TX block time), but the transaction was never confirmed.

**Comment by AndreiD** [comment]
so the transaction SHOULD go though but the way the JavaScript library is done it's wrong.
(tested on version 11, name "1.46, code name "constantin-0-pl")
I need to get the tx hash as soon as I send the transaction so I show it to the user or to another screen (possibly).
then I (the app) must pool to get it's status: confirmed, reject and NOT the javascript library.

I'm waiting either for LaksaJ to implement transactions or for LaksJSBundle to update their code. 

I'll keep this issue opened and closed it after they are fixed.
