### ISSUE TITLE
Bug: Keyboard appearance

### ISSUE THREAD

**Issue by snowsledge** [AndreiD/xzil-wallet#13]
When sending a transaction, the `To` and `Amount` field creates a popup keyboard to allow users to key in the address and ZIL amount respectively. However, once the popup occurs, the keyboard does not redact after, resulting in the keyboard appearing in the `Confirm Payment` screen. 

This will result in the `Send` button in the `Confirm Payment` screen to be blocked from being clicked by the wallet User.

**Comment by AndreiD** [comment]
please recheck on the new published version (    versionCode 11, versionName "1.46")

**Comment by snowsledge** [comment]
Could I check with you which keyboard are you using to develop? Samsung keyboard doesn't retract still.

**Comment by AndreiD** [comment]
the default one.. I'll try another method.
